# Generated by Django 2.0.6 on 2018-07-17 04:13

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=15)),
                ('student_last_name', models.CharField(max_length=15)),
                ('student_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('accommodations', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_first_name', models.CharField(max_length=15)),
                ('teacher_last_name', models.CharField(max_length=15)),
                ('teacher_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('departments', models.CharField(max_length=50)),
                ('room_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('teacher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='schoolpass.Teacher')),
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolpass.Student')),
                ('kind_of_pass', models.CharField(choices=[('WF', 'Water Fountain'), ('RR', 'Sophomore'), ('N', 'Nurse'), ('O', 'Office'), ('OC', 'Other Classroom')], default='WF', max_length=15)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            bases=('schoolpass.student', 'schoolpass.teacher'),
        ),
    ]
