# Generated by Django 2.0.6 on 2018-07-17 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolpass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='accommodations',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(default='No notes'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
