# Generated by Django 2.0.6 on 2018-07-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolpass', '0002_auto_20180717_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='password',
            new_name='teacher_password',
        ),
        migrations.AddField(
            model_name='student',
            name='number_of_passes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='number_of_rejections',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='password', max_length=25),
        ),
    ]
