# Generated by Django 2.0.6 on 2018-08-07 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolpass', '0002_auto_20180807_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='room_number',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
