# Generated by Django 2.0.6 on 2018-08-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolpass', '0002_auto_20180807_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pass_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pass_rejections',
            field=models.IntegerField(default=0),
        ),
    ]
