# Generated by Django 2.0.6 on 2018-08-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolpass', '0003_auto_20180809_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pass_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pass_rejections',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
