# Generated by Django 2.0.6 on 2018-07-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolpass', '0003_auto_20180718_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(max_length=25),
        ),
    ]
