# Generated by Django 2.0.6 on 2018-08-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolpass', '0003_auto_20180807_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classes',
            field=models.TextField(blank=True),
        ),
    ]
