# Generated by Django 2.0.6 on 2018-08-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolpass', '0004_auto_20180809_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes_enrolled',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes_taught',
            field=models.TextField(max_length=150),
        ),
    ]
